# Generated by Django 6.0.7 on 2026-07-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
