# Generated by Django 6.0.7 on 2026-07-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0002_alter_link_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
