# Generated by Django 6.0.7 on 2026-07-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0004_alter_link_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="short_code",
            field=models.CharField(db_index=True, max_length=6, null=True),
        ),
    ]
