# Generated by Django 6.0.7 on 2026-07-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0005_alter_link_short_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="url",
            field=models.URLField(max_length=500),
        ),
    ]
